### ISSUE TITLE
keyboard-colors.json not found

### ISSUE THREAD

**Issue by grantfreese** [withinboredom/system-76-keyboards#23]
**Description:**
The deb installer creates /etc/keyboard-color.json ('color' without an s), but the application appears to look for /etc/keyboard-colors.json ('color' with an s)

**Environment:**
* PopOS 19.04
* Cinnamon desktop
* Deb install of 1.1.0-beta5

**Error message:**
```
gfreese@pop-os:~$ which keyboard-color
/usr/bin/keyboard-color
gfreese@pop-os:~$ sudo keyboard-color run
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libX11' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibX11: cannot open shared object file: No such file or directory
   at keyboards.Installer.XOpenDisplay(String displayName)
   at keyboards.Installer.RootHasPermission()
   at keyboards.Program.GetFilters(IConfiguration configuration, Boolean dim, IControlContainer container)
   at keyboards.Program.GetKeyboard(IControlContainer container, IConfiguration configuration)
   at keyboards.Program.RunOrInstall(Options options)
   at keyboards.Program.<>c.<Main>b__7_2(RunOptions o)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 notParsedFunc)
   at keyboards.Program.Main(String[] args)
Aborted
gfreese@pop-os:~$ 

```

**Other notes:**
* Haven't tried building/running from source yet
* Renaming keyboard-color.json to keyboard-colors.json results in a different error about being unable to load libX11 or one of its dependencies. (Probably a different issue, but that's a problem for tomorrow's me.)

**Comment by withinboredom** [comment]
> libX11

Thanks, I probably need to add `libX11` as a dependency to the .deb and ensure it's only needed when the setting is set to `true`.

> creates /etc/keyboard-color.json ('color' without an s)

:man_facepalming:

**Comment by withinboredom** [comment]
I'm not sure the dim when screen off will work on Cinnamon, but you can find out with the following command:

```
for i in {1..100}; do xset q; date ; sleep 5; done
```

Then try turning off the screen by locking it. You're looking for 

```
Monitor is Off
```

to be in the output.
